"""Initial users records and photos

Revision ID: a23209127576
Revises: 
Create Date: 2021-06-12 20:17:03.512833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23209127576'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('username', sa.String(length=256), nullable=True),
        sa.Column('first_name', sa.String(length=256), nullable=True),
        sa.Column('last_name', sa.String(length=256), nullable=True),
        sa.Column('lang', sa.String(length=64), nullable=True),
        sa.Column('joined_dt', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'tasting_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('dt', sa.DateTime(timezone=True), nullable=False),
        sa.Column('wine_name', sa.String(length=128), nullable=False),
        sa.Column('region', sa.String(length=128), nullable=False),
        sa.Column('grapes', sa.String(length=256), nullable=False),
        sa.Column('vintage_year', sa.Integer(), nullable=True),
        sa.Column('experience', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'wine_photos',
        sa.Column('id', sa.String(length=128), nullable=False),
        sa.Column('tasting_record_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['tasting_record_id'], ['tasting_records.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wine_photos')
    op.drop_table('tasting_records')
    op.drop_table('users')
    # ### end Alembic commands ###
